### ISSUE TITLE
Following Idiomatic JS

### ISSUE THREAD

**Issue by gaurav21r** [dojo/guidelines#3]
Our organisation is looking into having a documented consistent Style guide for JS / TS and dince we've been long term users / contributors to Dojo, I stumbled across this.

Out of curiosity, did the core team consider https://github.com/rwaldron/idiomatic.js

If so, any reasons why this was not chosen?

Seems to be standard within the community, makes sense and quite extensive too (translated into various languages etc)!

**Comment by kitsonk** [comment]
While Idiomatic JavaScript that you mention is not bad, it conflicts with some of the standards we prefer to use, and while it has some good core principles, it wouldn't necessarily provide all the clarity needed to provide guidelines.  Also, since Dojo 2 will be TypeScript based, there are some other idioms that need to be used that Idiomatic JavaScript doesn't address.

Some specific examples, Idiomatic JavaScript recommends:
```javascript
if ( expression ) {
  // statements
}
```

Instead we prefer:
```javascript
if (expression) {
    // statements
}
```

Small things like two-space indentation, versus four-space indentation.  Using one `var` per scope, versus our preferred `let`/`const` per item.  Because also `let` and `const` are block scoped, the clarity of having all `var`s declared at the top of the scope goes away.

They also recommend the following:
```javascript
if ( expression ) {
  // statements
} else {
  // statements
}
```

While we prefer:
```javascript
if (expression) {
    // statements
}
else {
    // statements
}
```

The don't assert a preference for single or double quotes, though they recommend being consistent.  We enforce single.

They use `+` and `!!` for coercion, we want `Number()` and `Boolean()`.

So while at broad levels we would agree, there are some thing it is explicit about we don't want and then there are things that it is broad about which we are very specific, though the fundamental thoughts are largely shared.

**Comment by kfranqueiro** [comment]
For what it's worth, idiomatic.js was definitely one inspiration back when we looked at style guides, but as Kitson explains, there's definitely places where we have our own opinion, and where TS either influences our decisions or requires adding additional considerations.

For instance, I used to be more of a fan of coersion via `+` and `!!` rather than `Number(...)` or `Boolean(...)` as well, because I thought the latter is way too easy for inexperienced developers to accidentally shove `new` in front of (which doesn't do the same thing), but TypeScript will prevent you from making that mistake.

**Comment by gaurav21r** [comment]
Got it! We too follow the Dojo approach! So much cleaner :smile: !
TS - JS is definitely the biggest difference!
